version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db